# Only mutate your own application source code (exclude test files)
paths_to_mutate:
  - server/src

# Directory where your test files are located
tests_dir: server/test

# Use existing coverage data to skip lines that are never executed by tests (faster)
use_coverage: true

# Command used to run tests; keep it simple for speed
runner: "pytest -q"

# Maximum execution time (in seconds) allowed for each mutant before timing out
timeout: 10
